name: "Generate output"

on:
  push:
    branches: [main]
    tags: ["v*"]
    paths:
      - "*.kicad_sch"
      - "*.kicad_pcb"
      - ".github/workflows/ci.yml"
      - "pedalboard-hw.kibot.yaml"
  pull_request:
    paths:
      - "*.kicad_sch"
      - "*.kicad_pcb"
      - ".github/workflows/ci.yml"
      - "pedalboard-hw.kibot.yaml"
  repository_dispatch:
    types: [run_qs]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto_full:latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: KiBot
        run: |
          kibot -e pedalboard-hw.kicad_sch -d generated

      - name: Remove 3D Model (too large for github)
        run: |
          rm -f generated/3D/pedalboard-hw-3D.step

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated_outputs
          path: generated

      - name: Deploy latest to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: generated
          target-folder: latest
          clean-exclude: |
            v*
            index.html

      - name: Deploy index redirect
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          mkdir -p redirect
          echo '<meta http-equiv="refresh" content="0;url=latest/Browse/pedalboard-hw-navigate.html">' > redirect/index.html

      - name: Deploy index to root
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: redirect
          clean: false

      - name: Deploy versioned to GitHub Pages
        if: startsWith(github.ref, 'refs/tags/v')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: generated
          target-folder: ${{ github.ref_name }}
          clean-exclude: |
            v*
            latest
            index.html
